// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dmblcahqblckmagsqzap.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRtYmxjYWhxYmxja21hZ3NxemFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxMTI2ODksImV4cCI6MjA1ODY4ODY4OX0.qjDCJMsRKN9u77dDrL4mbQ06YNkPXbje6SJQ5bCI8vU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);